import './src/styles/global.css'

import "@fontsource/montserrat/300.css"
import "@fontsource/montserrat/400.css"
import "@fontsource/montserrat/500.css"
import "@fontsource/montserrat/600.css"
import "@fontsource/montserrat/700.css"
import "@fontsource/montserrat/300-italic.css"
import "@fontsource/montserrat/400-italic.css"
import "@fontsource/montserrat/500-italic.css"
import "@fontsource/montserrat/600-italic.css"
import "@fontsource/montserrat/700-italic.css" 

import "@fontsource/raleway/300.css"
import "@fontsource/raleway/400.css"
import "@fontsource/raleway/500.css"
import "@fontsource/raleway/600.css"
import "@fontsource/raleway/700.css" 
import "@fontsource/raleway/300-italic.css"
import "@fontsource/raleway/400-italic.css"
import "@fontsource/raleway/500-italic.css"
import "@fontsource/raleway/600-italic.css"
import "@fontsource/raleway/700-italic.css" 